bank:
    url: https://api.modulbank.ru
    accountId: ACCOUNT_ID
    token: TOKEN

paymentInUsd: 2000

#Create an invoice every Wednesday at 23.00
invoiceCreationTime: '0 0 23 * * WED'

invoiceEmail:
    addressee: ADDRESSEE_EMAIL
    subject: Invoice
    text: New invoice is generated

spring:
    mail:
        host: smtp.gmail.com
        port: 587
        from: FROM_EMAIL
        username: USERNAME
        password: PASSWORD
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true